### ISSUE TITLE
script backup

### ISSUE THREAD

**Issue by gerisse** [GLMF/GLMF203#2]
Bjr
je me suis inspiré de votre script pour tenter de faire mes sauvegardes sur mon NAS . Merci !
Mais je voudrais bien , avant de le lancer reellement, voir les commandes qu'ils lancent  : j'ai testé en mettant `set -n  ` en debut de script, mais  sans succes . Sauriez vous comment faire ?
Merci
Cdlt

**Comment by gerisse** [comment]
je me réponds moi meme ;-) : il faut mettre` set -x`

**Comment by tcolombo** [comment]
Bonjour,
Euh... et bien vous avez trouvé avant que je ne puisse répondre, tant mieux :-)
Cdlt
